node:
  ingress:
    create: true
    className: traefik
    hosts:
      - host: kuack-node.localhost
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: traefik

agent:
  ingress:
    create: true
    className: traefik
    hosts:
      - host: kuack-agent.localhost
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: traefik
